version: '3'

services:
  hadoop-master:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "50070:50070"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
    stdin_open: true
    tty: true

  hadoop-slave1:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    networks:
      - hadoop
    ports:
      - "8040:8042"
    stdin_open: true
    tty: true

  hadoop-slave2:
    image: liliasfaxi/spark-hadoop:hv-2.7.2
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    networks:
      - hadoop
    ports:
      - "8041:8042"
    stdin_open: true
    tty: true

networks:
  hadoop:
    driver: bridge